sudo: true
language: python

python:
  - "3.6"

before_install:
  - sudo apt-get update -qy
  - sudo apt-get install -y python-dev python-pip
  - pip install pipenv
  - pipenv install

script:
  - pipenv run python -m unittest discover
